blank_issues_enabled: false

contact_links:
  - name: Questions
    url: https://github.com/muhammadsammy/tailwindcss-classnames/discussions/new
    about: Please ask and answer questions or any discussions here.
