on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: tailwindcss-classnames
